deepset-ai/haystack-integrations

- integrations/fastrag.md
Adding the fastRAG repo by Intel Labs.
> add fastRAG

- .github/workflows/publish_integrations.yml
- integrations/azure-translator.md
- integrations/fastrag.md
- integrations/lemmatize.md
- integrations/qdrant-document-store.md
- Added "layout" to the integrations front matter
- Added Github action to rebuild Haystack Home
> add layout to frontmatter, github action

- integrations/veracity.md
Add details about the Veracity node that Xceron wrote.
> Add Veracity node by Xceron.

- integrations/azure-translator.md
- integrations/basic-agent-memory.md
- integrations/fastrag.md
- integrations/qdrant-document-store.md
- integrations/text2speech.md
- integrations/veracity.md
@ZanSara I created this page. Would be great if you can have a look too
> Adding text to speech page

- integrations/azure-translator.md
- integrations/lemmatize.md
Add pypi information for my 2 nodes.
> Add pypi info for my nodes

- integrations/entailment-checker.md
The image was not displayed.
This PR should fix the issue...
> Entailment-checker: correctly show the image

- integrations/elasticsearch-document-store.md
- integrations/faiss-document-store.md
- integrations/opensearch-document-store.md
- integrations/pinecone-document-store.md
- integrations/weaviate-document-store.md
> Update DocumentStore integrations

- integrations/chroma-documentstore.md
Minor lg updates and added a missing link.
> Docs: Update chroma doc

- integrations/elasticsearch-document-store.md
- integrations/huggingface.md
> Add 2.0 updates

- integrations/jina.md
This PR updates the Jina AI integration page with high-level information about the company and embeddings integration.
> add Jina AI's company information

- integrations/pinecone-document-store.md
I'm adding a section to the integration page,
which describes how to use Pinecone in Haystack 2.x.
In general, I tried to replicate the existing example.
> Pinecone: add section for 2.x integration

- integrations/ollama.md
Updating the current documentation with the chat generator 
@anakin87
> Add Ollama chat generator docs

- integrations/fastrag.md
fastRAG 2.0 is out with many new features.
Updated the readme to reflect all the new features.
> Update fastRAG 2.0 information

- integrations/ollama.md
part of https://github.com/deepset-ai/haystack-core-integrations/issues/209
> Update Ollama import paths

- integrations/amazon-bedrock.md
Sibling PR: https://github.com/deepset-ai/haystack-core-integrations/pull/220
Part of https://github.com/deepset-ai/haystack-core-integrations/issues/227
> chore!: Rename model_name to model in AmazonBedrockGenerator model card

- integrations/unstructured-file-converter.md
Part of https://github.com/deepset-ai/haystack-core-integrations/issues/205
(Also related to the recent refactor in https://github.com/deepset-ai/haystack-core-integrations/issues/221)
> Update Unstructured integration

- integrations/cohere.md
Sibling PR: https://github.com/deepset-ai/haystack-core-integrations/pull/222
Part of https://github.com/deepset-ai/haystack-core-integrations/issues/227
> chore!: Rename model_name to model in the Cohere integration

- integrations/instructor-embedder.md
Sibling PR: https://github.com/deepset-ai/haystack-core-integrations/pull/229
Part of https://github.com/deepset-ai/haystack-core-integrations/issues/227
> chore!: Rename model_name_or_path to model in Instructor model card

- integrations/jina.md
Sibling PR: https://github.com/deepset-ai/haystack-core-integrations/pull/230
Part of https://github.com/deepset-ai/haystack-core-integrations/issues/227
> chore!: Rename model_name to model in Jina model card

- integrations/llama_cpp.md
Part of https://github.com/deepset-ai/haystack-core-integrations/issues/177
Adds Integration page for [llama-cpp-haystack](https://github.com/deepset-ai/haystack-core-integrations/tree/main/integrations/llama_cpp).
> Add llama.cpp Integration

- integrations/cohere.md
Updates docs for cohere. Please verify the generator docs part. It's needlessly complicated IMHO If you agree adjust it to be similar to  CohereChatGenerator example
> Update cohere docs after project layout update, adding chat model

- integrations/fastrag.md
- Removed not rendered Github emojis
- Fixed readme
> Minor fixes to fastRAG readme

- integrations/assemblyai.md
- integrations/huggingface.md
- integrations/instructor-embedder.md
- integrations/llama_cpp.md
- integrations/lmformatenforcer.md
- integrations/mastodon-fetcher.md
- integrations/openai.md
- integrations/pinecone-document-store.md
- integrations/voyage.md
Fixes https://github.com/deepset-ai/haystack/issues/6909
> Fix affected snippets after the breaking changes

- integrations/amazon-bedrock.md
Add doc usage example for AmazonBedrockChatGenerator
> chore: Update amazon-bedrock tile for AmazonBedrockChatGenerator

- integrations/qdrant-document-store.md
Related to https://github.com/deepset-ai/haystack-core-integrations/issues/372
> docs: Update qdrant docs with changes to secret management

- integrations/jina.md
part of https://github.com/deepset-ai/haystack-core-integrations/issues/366
> update jina page - new secrets management

- integrations/google-ai.md
part of https://github.com/deepset-ai/haystack-core-integrations/issues/376
> Google AI - update integration page for new secrets mgmt

- integrations/instructor-embedder.md
part of https://github.com/deepset-ai/haystack/issues/7000
> update instructor integration page to reflect new devices mgmt

- integrations/fastembed.md
Hi I added the integration tile for `fastembed-haystack`.
[related issue](https://github.com/deepset-ai/haystack-core-integrations/issues/358)
> added fastembed integration tile

- integrations/amazon-bedrock.md
part of https://github.com/deepset-ai/haystack-core-integrations/issues/181
> Bedrock - add a section about embedders

- integrations/mongodb.md
part of https://github.com/deepset-ai/haystack-core-integrations/issues/143
minor improvements to the integration page
> Improve MongoDB integration page

- integrations/uptrain.md
Hey guys, 
There was a bug in the script in the api_key part. Found the correct usage [here](https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/uptrain/example/example.py). Have applied the same.
Thanks
> Fix bug in uptrain.md

- integrations/neo4j-document-store.md
> fix: Update neo4j-document-store.md

- integrations/pgvector-documentstore.md
Add keyword retrieval usage example to md
> Fixes deepset-ai/haystack-core-integrations#726

- integrations/huggingface.md
- part of https://github.com/deepset-ai/haystack/issues/7500
- other improvements
> improvements on Hugging Face integration page

- integrations/fastembed.md
Added the links to relevant notebooks in the cookbook.
> fastembed: add links to cookbook

- integrations/unstructured-file-converter.md
Link changed for unstructured docs
> docs: Update unstructured-file-converter.md

- integrations/fastrag.md
> fastRAG v3, compatible with Haystack v2

- integrations/mixedbread-ai.md
Updating the docs with the available rerankers :)
> Add mixedbread reranker docs

- integrations/fastrag.md
Update installation to use `pypi` flow.
> Update fastRAG installation flow.

- integrations/anthropic.md
- integrations/cohere.md
- integrations/context-ai.md
- integrations/langfuse.md
- integrations/mistral.md
Proposed Changes:
Replaced `DynamicChatPromptBuilders` with `ChatPromptBuilder` as the former is deprecated.
> fix: replace DynamicChatPromptBuilder

- integrations/arize-phoenix.md
- integrations/arize.md
One final pass at the integration
> docs: cleanup arize integration

- integrations/amazon-bedrock.md
- updated the Amazon Bed Rock Chat generators output example
> updated AmazonBedRock documentation

- integrations/cerebras.md
- integrations/google-ai.md
- integrations/groq.md
- integrations/monsterapi.md
- integrations/ollama.md
part of https://github.com/deepset-ai/haystack/issues/8621
> `ChatMessage` - access `text` instead of `content`

- .gitignore
- integrations/ragas.md
- https://github.com/deepset-ai/haystack-core-integrations/pull/1312
> The updated docs for Ragas-Haystack Integration

- integrations/ragas.md
brought up by a community member on discord
> remove duplicate lines of code from Ragas example

- integrations/mcp.md
Related to https://github.com/deepset-ai/haystack/issues/9137
> Update MCPTool import in code example

- integrations/amazon-bedrock.md
Fixes https://github.com/deepset-ai/devrel-board/issues/582
Covers some of the changes mentioned in https://github.com/deepset-ai/haystack-core-integrations/issues/1673
* Encourage `AmazonBedrockChatGenerator` rather than `AmazonBedrockGenerator`
> Update the list of models in Amazon Bedrock

- integrations/vllm.md
> Update the author for vllm integration

- integrations/anthropic.md
* Name some of the latest models
* Remove the list of supported models (hard to maintain)
> Update Anthropic page
