integrations/qdrant-document-store.md

I'm providing some updated regarding the Qdrant integration. We've released a local mode, so using Qdrant is possible even without any server behind. We wanted to cover those cases a bit, because that's more suited for some specific scenarios.

Extend Qdrant description with local in-memory/on-disk storage mode

---

integrations/chainlit.md

The Chainlit screenshot doesn't appear in the [correspondent web page](https://haystack.deepset.ai/integrations/chainlit).
Let's try to use an absolute URL...

Use absolute URL for Chainlit screenshot

---

integrations/instructor-embedder.md

This PR adds the Instructor Embedders to the list of integrations.
The Instructor Embedders component is used for computing embeddings using INSTRUCTOR embedding models - built for Haystack 2.0.
**Related PR:** 
https://github.com/deepset-ai/haystack-extras/pull/32

Add integration page for `Instructor Embedders`

---

integrations/instructor-embedder.md
integrations/vllm.md

Does tagging this as Model Provider make more sense for navigation? In my view it does? Wdyt @masci @bilgeyucel

Change tags to "Model Provider"

---

integrations/instructor-embedder.md

`MemoryDocumentStore` and related Retrievers have been renamed.
This PR fixes outdated documentation.

Rename `MemoryDocumentStore` to `InMemoryDocumentStore`

---

integrations/instructor-embedder.md

The `INSTRUCTOR-Embedders` package has been updated in https://github.com/deepset-ai/haystack-core-integrations/pull/44 to support the refactored `Document` class. It has also been bumped to the new version in https://github.com/deepset-ai/haystack-core-integrations/pull/46.
This PR updates the examples on the integration page to comply with the refactored `Document` class and the new `INSTRUCTOR-Embedders` release.
@TuanaCelik @masci

Update `INSTRUCTOR-Embedders` examples with refactored `Document` class

---

integrations/opensearch-document-store.md

Added 2.0 section and TOC to the opensearch integrations page. Personally, I liked two separate pages more. Would make it easier to filter for 2.x vs. 1.x integrations. Pages now become longer and description and pypi link need to be shard now. Advantage is that we only have exactly one page about opensearch integrations so it doesn't look like duplicates in the overview.

 Add OpenSearchDocumentStore and Retrievers 2.0 to existing page

---

integrations/cohere.md

Running this code in order to update the integration docs, I ran into this error:
```
DocumentStoreError: The embedding size of the query should be the same as the embedding size of the Documents. Please make sure that the query has been embedded with the same model as the Documents.
```
Updating the model to v3.0 fixes the error and the code runs as expected.

update Cohere model to embed-multilingual-v3.0

---

integrations/weaviate-document-store.md

SyntaxError because the interpreter expects the closing quote to match the opening one. To avoid this error, make sure to use the same type of quote for both the opening and closing of the string.

bug: Fixed Mismatched Quotes for host

---

integrations/qdrant-document-store.md

Part of deepset-ai/haystack-core-integrations#121

Update Qdrant integration for Haystack 2.x

---

integrations/elasticsearch-document-store.md

fixes https://github.com/deepset-ai/haystack-integrations/issues/98
test strategy:
output:
```
{'retriever': {'documents': [Document(id=6383dc3ed51fc90c2e45704853a7ad9b14168f4f262ac7a0b65e02c465d0bb1c, content: 'Historic Areas of Istanbul
With its strategic location on the Bosphorus peninsula between the Balkan...', meta: {'file_path': 'filename.txt', 'source_id': 'bb4b4bbec446c13f103bd0ec1777cbb424ae6d2bef355b17a5e299e97e9d4f55'}, score: 0.82134724, embedding: vector of size 1024)]}}
```

add working query pipeline example code to elasticsearch-document-store.md

---

integrations/assemblyai.md

Before: 
Note: Calling `indexing.run()` blocks until the transcription is finished.
After:
Note: Calling `preprocessing_pipeline.run()` blocks until the transcription is finished.

Corrected the pipeline name in the description

---

integrations/amazon-sagemaker.md

Fixes https://github.com/deepset-ai/haystack-core-integrations/issues/292

feat: add Sagemaker integration

---

integrations/pgvector-documentstore.md

part of https://github.com/deepset-ai/haystack-core-integrations/issues/142

Add pgvector

---

integrations/pinecone-document-store.md

part of https://github.com/deepset-ai/haystack-core-integrations/issues/395

Pinecone: rename retriever

---

integrations/astradb.md

part of https://github.com/deepset-ai/haystack-core-integrations/issues/394

Rename Astra Retriever

---

integrations/cohere.md

Related to https://github.com/deepset-ai/haystack-core-integrations/issues/370

docs: Update cohere docs with changes to secret management

---

integrations/gradient.md

Part of https://github.com/deepset-ai/haystack-core-integrations/issues/377
I also replaced the link to the outdated Colab with that present in the cookbook

Gradient - update page for new secrets mgmt

---

integrations/vllm.md

update vLLM integration page

---

integrations/chroma-documentstore.md

The linked chroma notebook is outdated and won't work. As we already have example code, I suggest we remove the link. Alternative is to update the notebook.

[Chroma] Remove link to colab notebook

---

integrations/assemblyai.md
integrations/elasticsearch-document-store.md
integrations/pgvector-documentstore.md

The new beta release breaks the old import `from haystack.pipeline import Pipeline.` I changed it to `from haystack import Pipeline`, which is what we use in all other tutorials too.
Related PRs: https://github.com/deepset-ai/haystack/pull/6973 and https://github.com/deepset-ai/haystack-tutorials/pull/285

Update import path of `Pipeline` in example code

---

integrations/mongodb.md

Part of https://github.com/deepset-ai/haystack-core-integrations/issues/143
Blocked by https://github.com/deepset-ai/haystack-core-integrations/pull/413 and let's wait for the first release before publishing the tile.

MongoDB Atlas support in Haystack 2.0

---

integrations/astradb.md

Fixes a runtime error for that variable not being defined

Use the pre-defined `model` for the model name in Astra DB docs

---

integrations/google-ai.md
integrations/google-vertex-ai.md

part of https://github.com/deepset-ai/haystack-core-integrations/issues/600

Google integrations: change answers to replies

---

integrations/cohere.md

Updated the integration tile for Cohere ranker integration. 
Related issue: [Cohere Ranker](https://github.com/deepset-ai/haystack-core-integrations/issues/645)

Updated the integration tile for Cohere ranker

---

integrations/ollama.md

Updated the Ollama integration tile with an example for embedder.
Fixes https://github.com/deepset-ai/haystack-core-integrations/issues/652
Related issue: https://github.com/deepset-ai/haystack-core-integrations/issues/651

Update Ollama integration tile with an embedder example

---

integrations/fastembed.md

part of https://github.com/deepset-ai/haystack-core-integrations/issues/660
- add section on sparse embeddings to Fastembed page
- general improvements

Add section on sparse embeddings to Fastembed page

---

integrations/pinecone-document-store.md

Part of https://github.com/deepset-ai/haystack-core-integrations/issues/223
The Pinecone Document Store was upgraded to `pinecone-api>=3` in https://github.com/deepset-ai/haystack-core-integrations/pull/793.
I am updating the integration page.

update Pinecone integration page based on the new API

---

integrations/apify.md

The current link is pointing to: 
`https://github.com/https://github.com/apify`
`https://twitter.com/https://x.com/apify`
This should be fixed be removing URLs from social links

Correct links to Apify socials

---

integrations/google-ai.md
integrations/google-vertex-ai.md

Removed occurrences of deprecated `gemini-pro-vision` and `gemini-ultra`.
Related issue: [#1024](https://github.com/deepset-ai/haystack-core-integrations/issues/1024)

Remove deprecated Gemini models

---

integrations/ollama.md

Part of https://github.com/deepset-ai/haystack-core-integrations/issues/1062
After the release of `ollama-haystack==1.0.0`, the URLs used in the components should point to the base URL instead of specific endpoints.

Ollama - change URLs

---

integrations/weaviate-document-store.md

part of https://github.com/deepset-ai/haystack-core-integrations/issues/1060
I decided to put here an example of the embedded instance
and explicitly point users to docs for the self-hosted Docker version and WCS.

improve weaviate integration page

---

integrations/jina.md

Updated embedding doc for `jina-embedding-v3` model.

chore: update embedding doc

---

integrations/google-vertex-ai.md

`project_id` is not a mandatory variable any longer for initializing Vertex AI generators. Updated the integrations page to include this change.

fix: project_id is now optional param in google_vertex

---

integrations/google-vertex-ai.md

I'm replacing the Colab links with links to the notebook in cookbook.
(I will update the notebook there to reflect updates).

fix links to Vertex notebook

---

integrations/langfuse.md

- Just changing the title of a code example from RAG pipeline to pipeline with ChatGenerator, ChatPromptBuilder because that pipeline doesn't contain a retriever so it's not RAG.
- Remove deprecated `gpt-3.5.-turbo` model and use the default, which is `gpt-4o-mini` instead

docs: fix title of code example for Langfuse integration

---

integrations/qdrant-document-store.md

Hey 👋. Greetings from Qdrant.
We had a user copy the snippets from https://haystack.deepset.ai/integrations/qdrant-document-store as is.
Since `recreate_index` is set to `True`, the Qdrant collection kept on getting deleted and recreated after each call.
This PR updates the doc to avoid this confusion.

docs: Update usage in qdrant-document-store.md

---

integrations/google-vertex-ai.md

part of https://github.com/deepset-ai/haystack-core-integrations/issues/1440#issue-2881165596
[Google recommends upgrading](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions) from `gemini-1.5-pro` to `gemini-2.0-flash`
and
gemini-1.0-pro support in vertex-ai will end on April 9, 2025. gemini-pro is an alias for gemini-1.0-pro.

Upgrade gemini models to gemini-2.0-flash in examples

---

integrations/google-genai.md

1. Adds integration for Google GenAI Text Embedder and Document Embedder.
3. These embedders enable users to leverage Google GenAI's embedding models to enhance RAG (Retrieval-Augmented Generation) pipelines.

Add author info for Gary Badwal in Google GenAI integration (TextEmbedder & DocumentEmbedder)

---

integrations/weights-and-bias-tracer.md

In https://github.com/deepset-ai/haystack-core-integrations/pull/2038,
I changed the location of `WeaveConnector` for consistency with other integrations.
Since this is a breaking change, I released a new major version (1.0.0).
In this PR, I am fixing the import.

fix `WeaveConnector` import

---

integrations/jina.md

**Related Issue:** deepset-ai/haystack-core-integrations#2135
- Added comprehensive documentation for the new JinaDocumentImageEmbedder component
- Updated component references throughout the document to include the image embedder
- Added detailed Image Embedding section with code examples and supported models
- Added Image Embedding section around line 125 with complete usage examples
- Updated introduction to mention multimodal models for image embedding
- Updated component list from 2 to 3 components including JinaDocumentImageEmbedder
- Updated usage description to mention image-based embedding use cases
This documentation complements the JinaDocumentImageEmbedder implementation in haystack-core-integrations.

Updated Jina documentation, add DocumentImageEmbedder
